# Generated by Django 2.2.4 on 2021-04-20 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0002_auto_20210419_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 22, 51, 47, 23975)),
        ),
    ]
