# Generated by Django 2.2.4 on 2021-04-20 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0004_auto_20210419_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 23, 4, 15, 648368)),
        ),
    ]
