# Generated by Django 2.2.4 on 2021-04-21 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0005_auto_20210419_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 2, 22, 29, 335431)),
        ),
    ]
