# Generated by Django 2.2.4 on 2021-05-03 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0012_auto_20210501_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 20, 55, 29, 309757)),
        ),
    ]
