# Generated by Django 2.2.4 on 2021-05-04 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0014_auto_20210503_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 22, 18, 26, 43672)),
        ),
    ]
